title: Blog
author: Beatriz Ortiz
description: Descrição da Bia
theme: minima

# Layout
show_social: true         # show footer
show_excerpts: false       # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md"}
  - {file: "blog.md"}

plugins:
  - jekyll-remote-theme
  - jekyll-feed
